package ch09_exception.a_trycatch;

public class SimpleException {

    public static void main(String[] args) {
        // TODO: 다음 코드가 정상적으로 종료되도록 예외를 처리하시오.
        int[] intArray = { 10 };
            System.out.println(intArray[2]);
        System.out.println("프로그램 종료합니다.");

        // END
    }
}
